In [2]:
import solidhdf5 as sah
import numpy as np

print("testing code")

#stuff for "making" dataset 2
a1 = np.random.random((10,10,3))
#print(a1)
a2 = np.random.random((10,10,3))
#print(a2)
a3 = np.random.random((10,10,3))
#print(a3)
a4 = np.random.random((10,10,3))
#print(a4)

#storing data and testing that it does not overwrite 
sah.store(a1,'[R,G,B]','testproject','PTMChmw','PES','20210223','08:30','EA0000','PESlt1')
print()
sah.store(a2,'[R,G,B]','testproject','PTMChmw','PES','20210222','08:31','EA0000','PESlt_aft_dep1')
print()
sah.store(a3,'[R,G,B]','testproject','PTMC','XPS','20210222','08:32','EA0001','XPShome1')
print()
sah.store(a4,'[R,G,B]','testproject','PTMC','PES','20210223','08:33','EA0002','PES1')
print()
sah.store(a4,'[R,G,B]','testproject','PTMC','PES','20210223','08:33','EA0002','PES_aft_dep1')
print()
sah.store(a4,'[R,G,B]','testproject','PTMC','PES','20210223','08:33','EA0002','PES_aft_dep1')
print()

#loading data
data1 = sah.load('EA0000/PESlt1')
print(data1)
data2 = sah.load('EA0000/PESlt2')
print(data2)

#showing paths
sah.show()

testing code

New sample.
Creating new directory and dataset.
Stored as EA0000/PESlt1

Sample allready has a directory.
Name of dataset is unique.
Adding dataset to sample directory.
Stored as EA0000/PESlt_aft_dep1

New sample.
Creating new directory and dataset.
Stored as EA0001/XPShome1

New sample.
Creating new directory and dataset.
Stored as EA0002/PES1

Sample allready has a directory.
Name of dataset is unique.
Adding dataset to sample directory.
Stored as EA0002/PES_aft_dep1

Sample allready has a directory.
Name of dataset is not unique.
Exiting.

[[[5.92061677e-01 4.47626161e-01 7.48854458e-01]
  [4.75069199e-01 9.29929499e-01 8.12400614e-01]
  [4.14167538e-01 8.98191408e-01 8.41294640e-01]
  [7.24478261e-01 1.87462909e-02 5.48542694e-01]
  [4.29279476e-01 2.82016609e-01 9.11491767e-01]
  [6.62215367e-01 4.05141773e-01 3.65848035e-01]
  [5.00388871e-01 5.41443109e-05 2.66530167e-01]
  [7.33617338e-02 1.02567800e-01 3.59436865e-01]
  [1.24841858e-01 4.15016892e-01 7.56470085e-